languages:
  Ruby: true
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  flog:
    enabled: true
    config:
      score_threshold: 20.0
  markdownlint:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
